<footer class="page-footer small teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">help.ME</h5>
        <p class="grey-text text-lighten-4">All Rights Reserved. © 2017</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Autores</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://github.com/arthurbrito99">Arthur B.</a> - arthur.brito1999@outlook.com</li>
          <li><a class="grey-text text-lighten-3" href="https://github.com/LucasPMM">Lucas P.</a> - lucaspaulom@hotmail.com</li>
          <li><a class="grey-text text-lighten-3" href="https://github.com/wendervitor">Wender V.</a> - vitornogueira502@gmail.com</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright teal lighten-2">
    <div class="container">
    © Coltec-UFMG 2017 
    </div>
  </div>
</footer>